const Routes = {
	LOADING: 'LOADING',

	LOGIN_STACK: 'LOGIN_STACK',
	LOGIN_SCREEN: 'LOGIN_SCREEN',
	OTP_SCREEN: 'OTP_SCREEN',
	SET_PASSWORD_SCREEN: 'SET_PASSWORD_SCREEN',
	MAIN_APP: 'MAIN_APP', //DRAWER

	APP_INTRO: 'APP_INTRO',

	HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
	HOME_TABS: 'HOME_TABS', //HOME TABS

	HOME_SCREEN: 'HOME',
	PROFILE_SCREEN: 'STUDENTS',
	NOTIFICATION_SCREEN: 'NOTIFICATIONS',
};

export default Routes;
